import gymnasium as gym
import numpy as np


class FlattenObservationWrapper(gym.ObservationWrapper):
    """BAS wrapper to flatten the observation space and the observations itself
    generated by a `ObservationContainerWrapper`.
    """

    def __init__(self, env: gym.Env):
        super().__init__(env)

        self._observation_space = gym.spaces.flatten_space(env.observation_space)

    def observation(self, observation: list[np.ndarray]) -> np.ndarray:
        return gym.spaces.flatten(self.env.observation_space, observation)
